<?php
/**
 * @file
 * serignan_context_global.strongarm.inc
 */

/**
 * Implements hook_strongarm().
 */
function serignan_context_global_strongarm() {
  $export = array();

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'megamenu_menu_hoverwait';
  $strongarm->value = '400';
  $export['megamenu_menu_hoverwait'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'megamenu_menu_sizewait';
  $strongarm->value = '250';
  $export['megamenu_menu_sizewait'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'megamenu_menu_timeout';
  $strongarm->value = '500';
  $export['megamenu_menu_timeout'] = $strongarm;

  return $export;
}
